spring.application.name=spring-cloud-config-server
#configuring our server port
server.port=8888

spring.cloud.config.server.git.uri=file:///C:/Users/550005766/Spring_Boot_Project/spring-cloud-config-server/git-localconfig-repo