
spring.application.name=currency-exchange
server.port=8000

spring.datasource.url=jdbc:h2:mem:testdb


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true

eureka.client.service-url.default-zone=http://localhost:8761/eureka

#configuring-retry()'

resilience4j.retry.instances.sample-api.maxAttempts=5

resilience4j.retry.instances.sample-api.waitDuration=1s

resilience4j.retry.instances.sample-api.intervalFunction=exponential

resilience4j.rateLimiter.instances.default.limitForPeriod=2
resilience4j.rateLimiter.instances.default.limitRefreshPeriod=10s

resilience4j.bulkhead.instances.default.maxConcurrentCalls=10